2022-11-07 15:48:50,537 ERROR: Exception on /index [GET] [in C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\main\routes.py", line 9, in index
    return render_template('index.html',  title='Home')
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Jai\Desktop\Project Management Y2 (2022-23) - Assignment\ProjectManagementY2-2223\app\templates\base.html", line 33, in block 'navbar'
    <li><a href="/logout" >Logout</a></li>
  File "C:\Users\Jai\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'auth' is undefined
2022-11-08 13:59:28,982 INFO: Template - Name startup [in /Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/__init__.py:71]
2022-11-08 14:01:01,125 INFO: Template - Name startup [in /Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/__init__.py:71]
2022-11-08 14:03:07,582 INFO: Template - Name startup [in /Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/__init__.py:71]
2022-11-08 14:04:43,991 INFO: Template - Name startup [in /Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/__init__.py:71]
2022-11-08 14:07:30,832 INFO: Template - Name startup [in /Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/__init__.py:71]
2022-11-15 14:34:41,313 INFO: Template - Name startup [in /Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/__init__.py:71]
2022-11-15 14:34:55,924 ERROR: Exception on / [GET] [in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/main/routes.py", line 13, in index
    return render_template('index.html',  title='Home')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/badealaketu/Documents/Assignment/ProjectManagementY2-2223/app/templates/base.html", line 69, in block 'content'
    <li><a href="{{ url_for('auth.products') }}" >products</a></li>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.products'. Did you mean 'main.products' instead?
